version: '2'
services:
    mysqldb:
      image: mysql:5.6.33
      container_name: mysqldb
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=wordpress
      volumes:
        - ./mysqldb:/var/lib/mysql
        - ./support:/var/support
      ports:
        - "3300:3306"
    wordpress:
      build:
          context: .
          dockerfile: ./Dockerfile
      ports:
        - "8000:80"
      links:
          - mysqldb
      volumes:
        - ./webdocs:/var/www/sites
